"""Opinions

Revision ID: 5e605a519a6f
Revises: e7271588257a
Create Date: 2022-05-27 16:02:45.013815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e605a519a6f'
down_revision = 'e7271588257a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opinion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('opinion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'album_id')
    )
    op.create_index(op.f('ix_opinion_id'), 'opinion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opinion_id'), table_name='opinion')
    op.drop_table('opinion')
    # ### end Alembic commands ###
