"""Qualification

Revision ID: 7fdfad23ec4b
Revises: 467e35e9c52c
Create Date: 2022-05-19 20:05:52.965777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fdfad23ec4b'
down_revision = '467e35e9c52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualification_id'), 'qualification', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualification_id'), table_name='qualification')
    op.drop_table('qualification')
    # ### end Alembic commands ###
