"""Remove example model

Revision ID: 927c1856c72f
Revises: 7fdfad23ec4b
Create Date: 2022-05-19 20:15:14.599167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927c1856c72f'
down_revision = '7fdfad23ec4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_example_id', table_name='example')
    op.drop_table('example')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='example_pkey')
    )
    op.create_index('ix_example_id', 'example', ['id'], unique=False)
    # ### end Alembic commands ###
